In [1]:
import numpy as np 
class Perceptron(object):
    def __init__(self, input_size, lr=1, epochs=10):
        self.W = np.zeros(input_size+1)
        self.epochs = epochs
        self.lr = lr

    def activation_fn(self, x):
        return 1 if x >=0 else 0

    def predict(self, x):
        x = np.insert(x, 0, 1)
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a

    def fit(self, X, d): 
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y 
                self.W = self.W + self.lr * e * np.insert(X[i], 0, 1)

In [2]:
mp = Perceptron(5)

In [3]:
mp.activation_fn(-10)

0

In [4]:
x = np.asarray([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [5]:
mp.predict(x)

1

In [6]:
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

In [8]:
d = np.array([0,0,0,1])
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [9]:
perceptron = Perceptron(input_size=2)
perceptron.W

array([0., 0., 0.])

In [10]:
perceptron.fit(X,d)  # fit the model
perceptron.W

array([-3.,  2.,  1.])

In [11]:
perceptron.predict(np.asarray([0,0]))

0

# 1. Perceptron class tanımınında var olan fonksiyonları kısaca tanıtınız.
- Init: Perceptron sınıfının constructor'i.
- activation_fn: Bir diger adi "Heaviside adim fonksiyonu"dur. Net input ve unit adim fonksiyonu arg olarak gonderilir ve bunlarla cikti belirlenir. 
- predict: Aktivasyon fonksiyonunun ciktisina gore yeni verilerin etiketlenmesi icin tahmin yapar.
- fit: Perceptronu egitmek icin kullanilir. Denetimli ogrenme uygular.

# 2. XOR için verileri değiştirip çalışmasınızı gözlemleyiniz.  




In [12]:
d = np.array([0, 1, 1, 1])

perceptron.fit(X,d)

perceptron.W

array([-2.,  2.,  2.])

In [13]:
d = np.array([1, 1, 1, 0])

perceptron.fit(X,d)

perceptron.W

array([ 2., -2., -1.])

# 3. bu class ile dersimize kayıtlı 40 öğrenci için imza tanıması yapılırsa X ve d değerlerini ne olur, predict fonksiyonu nasıl kullanılır açıklayınız
Imzalar 60 x 120 en, boy degerlerine sahip siyah beyaz resimlere kaydedilmis olsun. X matrisi (40, 60, 120) olur. 40 ogrenciye ait n tane imzamiz olsa, her n elemani bir imzanin binary bit degerlerinin dizisi olur.

d = [1, 3, 8, ... , 39] gibi n tane deger iceren bir vektor olur. Dolayisiyla predict icin kullandigimiz aktivasyon fonksiyonunu softmax aktivasyon fonksiyonu ile degistirmemiz yararli olur.
Softmax bize bir ihtimal dizisi dondurur. Ogrencileri bir bit dizisinde sutunlarla temsil etmis olsaydik en yuksek float ihtimalin oldugu sutun, imzanin kime ait oldugu tahmininin o sutundaki ogrenciye tekabul ettigini isaret eder.


# 4. Bu modelin hatası nasıl elde edilir, kendi çözümünüzü/ yorumunuzu yazınız.
Mean Absolute Error veya Mean Square Error yontemlerinden birini kullanabiliriz.
Egitim sonucu buldugumuz sonuclarin gercek degerlere olan uzakliklarinin toplamlarina bakariz. Degerler aradasindaki fark ne kadar buyukse hata payimiz da o kadar buyuk olmus olur.

Ornek bir softmax ciktisi:

[0.01, 0.2, 0.35, 0.8 ...]

0.8 4. ogrenci

=> HATA = (0 - 0.01)^2 + (1 - 0.8)^2 + (0 - 0.2)^2 + ... + (0 - 0.35)^2 (Mean Square Error)
seklinde hesaplanir.